### PR TITLE
Tests/11 pytest

### PR DESCRIPTION
**Pull request by Batalex**
See https://github.com/canonical/operator/issues/1110.
This would be the last PR :tada:

### CODE REVIEW

**Comment by tonyandrewmeyer** [comment]
@Batalex could you please resolve the conflicts? Thanks!

**Comment by benhoyt** [comment]
@tonyandrewmeyer Could you please take a look at this. Looks like @Batalex has resolved conflicts.

**Comment by tonyandrewmeyer** [comment]
Included in #34 since I was adjusting other things at the same time, and this branch has some sort of issue that prevents merging in the Github UI.

**Comment by tonyandrewmeyer** [comment]
Thanks for all of these, by the way!

**Pull request closed without merging**
